# Generated by Django 5.2.6 on 2025-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(default='1st Term', max_length=100)),
                ('resumption_date', models.DateField()),
            ],
        ),
    ]
