# Generated by Django 5.2.6 on 2025-09-18 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_result_student_remove_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('first_term', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_term', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('third_term', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_results', to='core.student')),
            ],
        ),
    ]
